### ISSUE TITLE
NoMethodError - undefined method `refinery_help_tag' for #<#<Class:0x000000059a0830>:0x00000005981a70>:

### ISSUE THREAD

**Issue by forever-sumit** [parndt/seo_meta#28]
Hi,

I've followed the readme doc and after that when I'm starting my server and access the page where I've added the 

`<%= render 'seo_meta/form', form: f %>`

its giving me error for 

`NoMethodError - undefined method `refinery_help_tag' for #<#<Class:0x000000059a0830>:0x00000005981a70>:`

As I checked in this gem we have no where define method 'refinery_help_tag'

Let me know how can I resolve this issue.

Thanks in advance .

**Comment by parndt** [comment]
Hi - you're right! We don't define that helper.. and it's something from Refinery that we never removed when extracting to this gem.

**Comment by parndt** [comment]
Here is [the implementation in Refinery](https://github.com/refinery/refinerycms/blob/2c3b7c31314cc3fbcd425d7c461e14002bfda7fc/core/app/helpers/refinery/tag_helper.rb#L4-L10)

But probably we should just remove it from this gem?

**Comment by bricesanchez** [comment]
Fixed with #32
